# Site settings
title: bloggb
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog of Guillaume Bouvier
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: bougui505

# Build settings
markdown: kramdown

# Bibliography
scholar:
    sort_by: year
    order: descending
