# Site settings
title: bloggb
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog of Guillaume Bouvier
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bougui505.github.io" # the base hostname & protocol for your site
twitter_username: bougui505
github_username: bougui505

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# Bibliography
scholar:
    bibliography_template: bib
    sort_by: year
    order: descending

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
